### ISSUE TITLE
Replace TSLint with ESLint

### ISSUE THREAD

**Issue by iquabius** [iquabius/olimat#51]
[The future of TypeScript on ESLint (Jan 2019)](https://eslint.org/blog/2019/01/future-typescript-eslint)

- [x] Wait for v4 of [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier/pull/74#issuecomment-456484902)
- [x] Use [typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)

Example project: [eslint-config-react-native-wcandillon](https://github.com/wcandillon/eslint-config-react-native-wcandillon)

### babel-eslint limitations
See:
- [Possible to use `@babel/plugin-transform-typescript` with this?](https://github.com/babel/babel-eslint/issues/663#issuecomment-457316676)
- [11.0.0-beta.0](https://github.com/babel/babel-eslint/pull/711#issuecomment-456203896)

Use babel-eslint to [lint TypeScript with ESLint](https://www.youtube.com/watch?v=Pl2heYVwQ-Q)

~~We should compile API code with babel as well before we continue with this. Currently we're using 'ts-node' for dev env and `tsc` from 'typescript'.~~ This is actually not a good idea. See:

- [Babel7 or TypeScript](https://kulshekhar.github.io/ts-jest/user/babel7-or-ts)
> You’ll get a more fluent TDD experience (when using ts-jest) since files will be type-checked at the same time they’re compiled and ran.

Relacionado a #95.

**Comment by lydell** [comment]
eslint-config-prettier v4.0.0 is now released!
